# Clean up

Cleaning up code for future me & testing if things worked

In [3]:
# libraries
import sys; sys.path.insert(0, '..') # if you don't find it here, look one above
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import scipy.io as spio
import pickle
import warnings

from tqdm import tqdm
from scipy import stats
from scipy.ndimage import gaussian_filter1d
from io_utils import *
from plotting_utils import * 


# settings
%load_ext autoreload
%autoreload 2
sns.set_context("talk")

Test with single session

In [4]:
sess_name =  'data_sdc_20190902_145404_fromSD' 
base_path  = 'Y:\jbreda\ephys\post_sort_analysis\sorted_pre_bdata' 
beh_mat   = 'protocol_info.mat'
spks_mat  = 'ksphy_clusters_foranalysis.mat'


# create paths
sess_path = os.path.join(base_path, sess_name)
beh_path  = os.path.join(sess_path, beh_mat)
spks_path = os.path.join(sess_path, spks_mat)

# alginment info (hard coded here & in fx)
# names = ['aud1on', 'aud1off', 'aud2on', 'aud2off', 'trial_all', 'delay_overlap', 
#          'delay2s', 'trial2s', 'delay4s', 'trial4s']
# windows = [[-400, 600], [-500, 500], [-400, 600], [-500, 500], [-100, 5000], [-300, 2300],
#            [-150, 2150],[-200, 2400], [-150, 4150], [-200, 4400]]

# align_windows = dict(zip(names,windows))

Load in

In [11]:
beh_df, spks_dict = load_and_wrangle(beh_path, spks_path, overwrite=False)

sess_aligned, sess_windows = event_align_session(spks_dict, beh_df, sess_path, overwrite=True,
                                                 delay_mode=True, file_name='2021_05_06_cleanup_aligned_spks.pkl')

no file found, running alignment for session


In [40]:
beh_df[beh_df.loc[:,'first_sound'] == 'psycho']

trial_num hit_hist  delay  pair_hist correct_side prev_side  aud1_sigma  \
11          31     miss      2          9        RIGHT      LEFT    0.008904   
12          32      hit      2         12         LEFT     RIGHT    0.002704   
14          34      hit      2         13         LEFT      LEFT    0.004023   
17          39      hit      4          9        RIGHT      LEFT    0.008904   
18          41     miss      4         14         LEFT      LEFT    0.005985   
..         ...      ...    ...        ...          ...       ...         ...   
278        382      hit      2         10        RIGHT     RIGHT    0.013248   
280        384      hit      4          9        RIGHT      LEFT    0.008904   
289        398      hit      6         13         LEFT     RIGHT    0.004023   
292        402      hit      2         12         LEFT     RIGHT    0.002704   
293        403      hit      2         14         LEFT      LEFT    0.005985   

     aud2_sigma       c_poke    end_state    hit_state      aud1_on  \
11       0.0073   774.886224   779.965231   778.618222   774.937230   
12       0.0073   780.466227   785.484217   784.170224   780.517233   
14       0.0073   804.920227   809.897223   808.860225   804.971234   
17       0.0073   851.109224   858.071228   856.864217   851.160220   
18       0.0073   870.657223   877.925230   876.534220   870.707230   
..          ...          ...          ...          ...          ...   
278      0.0073  4930.042219  4935.248217  4933.920217  4930.092220   
280      0.0073  4951.623222  4958.737224  4957.602223  4951.673237   
289      0.0073  5184.165229  5193.525236  5192.218219  5184.216224   
292      0.0073  5241.322233  5246.522218  5245.159224  5241.373230   
293      0.0073  5251.930228  5256.937232  5255.634227  5251.980234   

        aud1_off      aud2_on     aud2_off  louder first_sound  
11    775.337228   777.337223   777.737223  psycho      psycho  
12    780.917230   782.916227   783.317224  psycho      psycho  
14    805.371231   807.371221   807.771221  psycho      psycho  
17    851.560236   855.559227   855.959231  psycho      psycho  
18    871.107233   875.108232   875.508222  psycho      psycho  
..           ...          ...          ...     ...         ...  
278  4930.492223  4932.492224  4932.892225  psycho      psycho  
280  4952.073227  4956.074223  4956.473226  psycho      psycho  
289  5184.616224  5190.615234  5191.015235  psycho      psycho  
292  5241.773230  5243.773224  5244.173227  psycho      psycho  
293  5252.381230  5254.381225  5254.781231  psycho      psycho  

[80 rows x 17 columns]

In [48]:
sess_aligned[0].keys()

dict_keys(['aud1on', 'aud1off', 'aud2on', 'aud2off', 'trial_all', 'delay_overlap', 'delay2s', 'trial2s', 'delay4s', 'trial4s'])

In [59]:
class Trial():
    def __init__(self,dval):
        self.delay=dval
        return None

        
trial0 = Trial(2)
trial1 = Trial(4)
trial2 = Trial(4)

type(trial0)

trial0.delay,trial1.delay

trialL = [trial0,trial1]
for trial in trialL:
    print(trial.delay)

print(trial0==trial1)
print(trial1==trial2)
print(trial1)
print(trial1.delay==trial2.delay)



2
4
False
False
True


In [ ]:
class Neuron():
    def __init__(self):
        return None
    
class Trial():
    def __init__(self):
        return None

In [73]:
class Trial():
    def __init__(self,dval,sptimes):
        self.delay=dval
        self.sptimes = sptimes
        return None
    
    def get_spikes(self,thresh):
        allspikes = np.array(self.sptimes)
        spikes = allspikes[allspikes>=thresh]
        return spikes

trial10 = Trial(dval=2,sptimes = [-2,-1,0,1,2])

print('spike times relative to middle of trial',trial10.sptimes)

print('spiketimes thresholded',trial10.get_spikes(0))


spike times relative to middle of trial [-2, -1, 0, 1, 2]
spiketimes thresholded [0 1 2]
[0 1 2]


In [ ]:
trial10 = Trial(dval=2,sptimes = [-2,-1,0,1,2])
trial11 = Trial(dval=4,sptimes = [-12,-1,0,1,2])

trialL = [trial10,trial11]
for trial in trialL:
    if trial.delay==2:
        print(trial.get_spikes(0))

In [47]:
L = sess_aligned[neuronn]['aud1on'][trialn]
L # what was delay time (2 or 4?)

array([-0.36830063, -0.35060157, -0.34836836, -0.34046878, -0.3394355 ,
       -0.29040477, -0.28437176, -0.22484159, -0.20457601, -0.14037942,
       -0.04878429,  0.01164583,  0.05794337,  0.06460968,  0.10664078,
        0.12880627,  0.14900519,  0.16513767,  0.16783752,  0.53265146,
        0.58614861])

In [30]:
trialn = 2
neuronn= 0 
event = 'aud1on'

sess_aligned[neuronn][event][trialn]

array([-0.36830063, -0.35060157, -0.34836836, -0.34046878, -0.3394355 ,
       -0.29040477, -0.28437176, -0.22484159, -0.20457601, -0.14037942,
       -0.04878429,  0.01164583,  0.05794337,  0.06460968,  0.10664078,
        0.12880627,  0.14900519,  0.16513767,  0.16783752,  0.53265146,
        0.58614861])

In [21]:
sess_windows

{0: {'aud1on': [-400, 600],
  'aud1off': [-500, 500],
  'aud2on': [-400, 600],
  'aud2off': [-500, 500],
  'trial_all': [-100, 5000],
  'delay_overlap': [-600, 2600],
  'delay2s': [-150, 2150],
  'trial2s': [-200, 2400],
  'delay4s': [-150, 4150],
  'trial4s': [-200, 4400]},
 1: {'aud1on': [-400, 600],
  'aud1off': [-500, 500],
  'aud2on': [-400, 600],
  'aud2off': [-500, 500],
  'trial_all': [-100, 5000],
  'delay_overlap': [-600, 2600],
  'delay2s': [-150, 2150],
  'trial2s': [-200, 2400],
  'delay4s': [-150, 4150],
  'trial4s': [-200, 4400]},
 2: {'aud1on': [-400, 600],
  'aud1off': [-500, 500],
  'aud2on': [-400, 600],
  'aud2off': [-500, 500],
  'trial_all': [-100, 5000],
  'delay_overlap': [-600, 2600],
  'delay2s': [-150, 2150],
  'trial2s': [-200, 2400],
  'delay4s': [-150, 4150],
  'trial4s': [-200, 4400]},
 3: {'aud1on': [-400, 600],
  'aud1off': [-500, 500],
  'aud2on': [-400, 600],
  'aud2off': [-500, 500],
  'trial_all': [-100, 5000],
  'delay_overlap': [-600, 2600],
  'de

In [20]:
sess_windows[3]['trial_all']

[-100, 5000]

Test changes to plotting functions here with the session, save out to somewhere new.

Hits, all delay types, 'delay_overlap'